language: node_js
node_js:
  - "stable"
install:
  - npm install
before_script:
  - npm install -g sequelize-cli
script:
  - npm test
addons:
    code_climate:
        repo_token: cd4494dc1d820cda82620359978bec8d1a4a82ba8fa249bb0448e879e88ad0e9