export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const ADD_TO_DOCUMENTS = 'ADD_TO_DOCUMENTS';
export const SET_DOCUMENTS_TO_STATE = 'SET_DOCUMENTS_TO_STATE';
