export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export const ADD_TO_DOCUMENTS = 'ADD_TO_DOCUMENTS';
export const SET_DOCUMENTS_TO_STATE = 'SET_DOCUMENTS_TO_STATE';
export const SET_SINGLE_DOCUMENT_TO_STATE = 'SET_SINGLE_DOCUMENT_TO_STATE';
export const CREATE_DOCUMENT_ERROR = 'CREATE_DOCUMENT_ERROR';
export const UPDATE_SINGLE_DOCUMENT = 'UPDATE_SINGLE_DOCUMENT';
